services:
  - type: web
    name: secshare
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: secshare-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: secshare-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: secshare-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: STORAGE_PATH
        value: /opt/render/project/src/uploads
      - key: PORT
        value: 8080

databases:
  - name: secshare-db
    databaseName: secshare
    user: secshare_user
    plan: free
